# Generated by Django 4.2.3 on 2023-07-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0003_remove_profile_city_remove_profile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
